### ISSUE TITLE
set_brightness() behavior change

### ISSUE THREAD

**Issue by lunatus** [pimoroni/microdot-phat#20] opened 2018-03-19 01:17 UTC
Just wanted to point out something. Perhaps it's somewhere in the documentation that I didn't read or was broken to begin with...

I had modified the canned clock example to flip the display and set the brightness to a lower value. This was working great until this evening when I did an apt-get update and got some new libs.

The error is:
Traceback (most recent call last):
  File "./clock.py", line 16, in <module>
    set_brightness(0.4)
  File "/usr/lib/python2.7/dist-packages/microdotphat/__init__.py", line 311, in set_brightness
    _mat[m_x][0].set_brightness(brightness)
NameError: global name '_mat' is not defined

Obviously, somebody didn't get initialized and to fix this problem one needs to call show() before the set brightness call.

Just pointing this out as something that changed, in case it was unintentional. 

-Ben

**Comment by Gadgetoid** [comment] 2018-03-19 10:28
This was absolutely unintentional, good spot! I'll release a fix for this ASAP.

This will, no doubt, have been caused by the shift to on-demand initialisation and the `set_brightness` method will be missing a call to setup.

It's what happens when you don't have good test coverage :(

**Comment by Gadgetoid** [comment] 2018-03-19 12:52
Fixed in 0.2.1, sorry about that!

**Closed as completed** 2018-03-19 12:52 UTC
Labels: bug

**Comment by lunatus** [comment] 2018-03-20 22:16
I just checked it out. Works again. Thanks for fixing it. I didn't want to dig through it myself the other night. I had had my own variable initialization adventure in Arduinoland at work last week and wasn't in the mood for another just then...
